### ISSUE TITLE
Improve handling of numbers as strings

### ISSUE THREAD

**Issue by lilyvanoekel** [briza-insurance/illogical#135]
For comparison expressions like `>`, `<`, `>=`, etc. treat numbers encoded as strings as numbers, using `parseInt` or `parseFloat`.

We've done something similar for `wegood`:
https://github.com/briza-insurance/wegood/blob/master/src/rule/range.ts#L30-L41

**Comment by lilyvanoekel** [comment]
@davidhorak if these expressions are used on strings that do not contain a valid number, should we error or return false like we do now when `isNumber` fails? Assuming returning false?

Do we need to handle numbers in scientific notations?

Should we omit currency signs so we don't fail on things like `$10.00 > $8.00`?

**Comment by davidhorak** [comment]
> if these expressions are used on strings that do not contain a valid number, should we error or return false like we do now when isNumber fails? Assuming returning false?

I would say error, as we do not want evaluate these in an "not predictable manner" from illogical perspective, i.e. errors.

> Do we need to handle numbers in scientific notations?

I would say no, as this may be tricky for large numbers.

> Should we omit currency signs so we don't fail on things like $10.00 > $8.00?

Yes. I would not recommend ignore these in the parsing, i.e. these should be unexpected strings, i.e. errors - from the illogical perspective.

**Comment by theslyone** [comment]
> > if these expressions are used on strings that do not contain a valid number, should we error or return false like we do now when isNumber fails? Assuming returning false?
> 
> I would say error, as we do not want evaluate these in an "not predictable manner" from illogical perspective, i.e. errors.
> 
A follow up on this @davidhorak, in the case of the `===` operator, we should return `false` if comparison fails instead of failing hard with an error because string equality is a valid comparison as well. We can error out for `>`, `<`, `<=` etc operators that indeed require numbers as operands.
