### ISSUE TITLE
NOT operator

### ISSUE THREAD

**Issue by davidhorak** [briza-insurance/illogical#33]
- To negate result of other expressions

#### Examples
- ```["NOT", ["IN", 1, [1, 2]]]``` -> **false**

**Comment by rthreei** [comment]
I remember a similar type of operator for v1 of question schema: `NOR`.

There's a case that needs to be consider:
- How does this operator evaluate when there is "no answer value" present?

**Comment by davidhorak** [comment]
```NOR``` is already implemented - https://github.com/briza-insurance/illogical#nor

> How does this operator evaluate when there is "no answer value" present?
- This operand, ```NOT``` is from the logical category, hence it follows the restrictions as the other logical operands, i.e. invalid expressions, captured by the evaluation process, will throw an error.

**Comment by rthreei** [comment]
> NOR is already implemented - https://github.com/briza-insurance/illogical#nor

Ah right.  Could you just use that?

**Comment by davidhorak** [comment]
Technically, yes!.
Will review with team, as they had couple of examples when it was handy for them --- will post it here, or it would be closed.

**Comment by davidhorak** [comment]
So the main benefit of this operand is the fact that it would be more verbose. Also the logical operands now expect 2+ operands, so we would have to adjust it this behavior.
