### ISSUE TITLE
Support conditions that need to be agnostic of undefined/null

### ISSUE THREAD

**Issue by lilyvanoekel** [briza-insurance/illogical#40]
Currently we have the option to compare a value against `null`, or to use the `UNDEFINED` comparison expression.

It would be nice if we had a way to cover both cases easily. 

For example, the following condition:

```
"condition": [
    "NOR",
    [
      "UNDEFINED",
      "$Loss1Date"
    ],
    [
      "==",
      "$Loss1Date",
      null
    ]
  ]
```

Say it's possible for `Loss1Date` to be on the page but left empty, or maybe conditionally not shown at all, or filled out, and then emptied by the user. By the time it comes to evaluate the condition it might be either `null` or `undefined`. It would be nice if we can capture that in a single expression.

Some options:
* `UNDEFINED_OR_NULL` expression
* Updating `UNDEFINED` to check for null as well
* `EMPTY` / `NOT_EMPTY` expression
* `NIL` / `NOT_NIL` expression

**Comment by davidhorak** [comment]
**PRESENT** 
 - is defined and not null
